const Discord = require('discord.js');
const brain = require('brain.js');

module.exports.run = async (bot, message, args) => {
  const phrase = args.join(' ');
  const network = new brain.recurrent.LSTM();
    network.train([
        { input: "Water", output: "Drink" },
        { input: "Juice", output: "Drink" },
        { input: "Lemonade", output: "Drink" },
        { input: "Coke", output: "Soda" },
        { input: "Sprite", output: "Soda" },
        { input: "Fanta", output: "Soda" },
        { input: "Pepsi", output: "Soda" },
        { input: "Mountain Dew", output: "Soda" },
        { input: "Los Angeles", output: "Place" },
        { input: "San Francisco", output: "Place" },
      { input: "Seattle", output: "Place" },
           { input: "Portland", output: "Place" },
           { input: "Minneapolis", output: "Place" },
     { input: "Philadelphia", output: "Place" },
           { input: "Toronto", output: "Place" },
           { input: "Atlanta", output: "Place" },
           { input: "Detroit", output: "Place" },
           { input: "Orlando", output: "Place" },
           { input: "Miami", output: "Place" },
           { input: "District of Columbia", output: "Place" },
           { input: "Baltimore", output: "Place" },
           { input: "Boston", output: "Place" },
           { input: "Cleveland", output: "Place" },
           { input: "New Delhi", output: "Place" },
           { input: "Mumbai", output: "Place" },
           { input: "Lahore", output: "Place" },
           { input: "Moscow", output: "Place" },
           { input: "Seoul", output: "Place" },
           { input: "Tokyo", output: "Place" },
           { input: "Kuala Lumpur", output: "Place" },
           { input: "Istanbul", output: "Place" },
           { input: "Singapore", output: "Place" },
           { input: "Dubai", output: "Place" },
           { input: "Paris", output: "Place" },
           { input: "0", output: "Number" },
           { input: "1", output: "Number" },
                 { input: "2", output: "Number" },
                 { input: "3", output: "Number" },
                 { input: "4", output: "Number" },
                 { input: "5", output: "Number" },
                 { input: "6", output: "Number" },
                 { input: "7", output: "Number" },
                 { input: "8", output: "Number" },
                 { input: "9", output: "Number" },
                 { input: "Dog", output: "Animal" },
                 { input: "Human", output: "Animal" },
      { input: "Cat", output: "Animal" },
                       { input: "Bird", output: "Animal" },
                       { input: "Deer", output: "Animal" },
                       { input: "Tiger", output: "Animal" },
                       { input: "Lion", output: "Animal" },
                       { input: "Fish", output: "Animal" },
                       { input: "JavaScript", output: "Programming" },
                             { input: "Python", output: "Programming" },
                             { input: "C++", output: "Programming" },
                             { input: "C", output: "Programming" },
                             { input: "C#", output: "Programming" },
                             { input: "Lua", output: "Programming" },
                             { input: "Java", output: "Programming" },
                             { input: "CoffeeScript", output: "Programming" },
                             { input: "TypeScript", output: "Programming" },
                             { input: "SQL", output: "Programming" },
                             { input: "HTML", output: "Web Development" },
                             { input: "CSS", output: "Web Development" },
                             { input: "Math", output: "Subject" },
                                   { input: "Science", output: "Subject" },
                                   { input: "English", output: "Subject" },
                                   { input: "History", output: "Subject" },
                                   { input: "Trigonometry", output: "Sub-Subject" },
                                   { input: "Probability", output: "Sub-Subject" },
                                   { input: "Algebra", output: "Sub-Subject" },
                                   { input: "Geometry", output: "Sub-Subject" },
      { input: "Biology", output: "Sub-Subject" },      
                                   { input: "Physics", output: "Sub-Subject" },
                                   { input: "Chemistry", output: "Sub-Subject" },
      
      
    ])
    const output = network.run(parseString(phrase));
    message.reply(`Prob: ${output}`);

}
module.exports.help = {
  name: "ml"
}
